#!/usr/bin/env node
/**
 * Generate Angular environment configuration from environment variables.
 * This script runs during Amplify build to inject runtime configuration.
 * 
 * Usage: node scripts/generate-env.js
 * 
 * Environment Variables:
 *   ANGULAR_APP_API_URL          - Backend API URL (e.g., http://54.167.150.136:8080)
 *   ANGULAR_APP_COGNITO_POOL_ID  - Cognito User Pool ID
 *   ANGULAR_APP_COGNITO_CLIENT_ID - Cognito Client ID (SPA)
 *   ANGULAR_APP_COGNITO_DOMAIN   - Cognito Domain
 *   ANGULAR_APP_COGNITO_REGION   - Cognito Region (default: us-east-1)
 */

const fs = require('fs');
const path = require('path');

// Configuration from environment variables with defaults
const config = {
    production: true,
    apiUrl: process.env.ANGULAR_APP_API_URL || 'http://localhost:8080',
    cognito: {
        userPoolId: process.env.ANGULAR_APP_COGNITO_POOL_ID || 'us-east-1_TDmsHjRgU',
        userPoolWebClientId: process.env.ANGULAR_APP_COGNITO_CLIENT_ID || '455m33j66v54q1m05892550186',
        domain: process.env.ANGULAR_APP_COGNITO_DOMAIN || 'cloud-infra-lite-dev-3ubmtss0.auth.us-east-1.amazoncognito.com',
        region: process.env.ANGULAR_APP_COGNITO_REGION || 'us-east-1'
    }
};

// Generate environment.ts content
const content = `// Auto-generated by generate-env.js - DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}
export const environment = ${JSON.stringify(config, null, 2)};
`;

// Write to environment.ts (used by Angular build)
const envPath = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');

fs.writeFileSync(envPath, content);
console.log(`✅ Environment generated: ${envPath}`);
console.log(`   API URL: ${config.apiUrl}`);
console.log(`   Cognito Pool: ${config.cognito.userPoolId}`);
